name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Caching npm dependencies for faster builds
          cache-dependency-path: 'package-lock.json'  # Specify path for cache

      - name: Install dependencies
        run: npm install

      - name: Build with Webpack
        run: npx webpack

      - name: Run tests
        run: npm test
