name: NodeJS with Next.js and Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # Caching npm dependencies for faster builds
        cache-dependency-path: '**/package-lock.json'  # Use wildcard to ensure path resolution

    - name: Install dependencies
      run: npm ci  # Use npm ci for clean install

    - name: Build with Webpack
      run: npx webpack

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: 'path/to/your/artifact'

    - name: Run tests
      run: npm test
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_DOTCOM_TOKEN }}

